FROM public.ecr.aws/lambda/python:3.11

# pipの最新化
RUN pip install --upgrade pip

# ライブラリインストール
COPY requirements.txt .
RUN pip install -r requirements.txt

# アプリケーションをコピー
COPY . .

# UvicornでFastAPIを起動（Lambda用ハンドラーに対応）
CMD ["main.handler"]
